# Makefile for x86 16 bit UNIX assembller
#
# Author: Andrei Rabusov <arabusov@gmail.com>
#         2022-10-22
#
CC=gcc
CFLAGS=-ansi -pedantic -Wall -Wextra -Werror -Wfatal-errors -g -ggdb
LD=$(CC)
LDFLAGS=-g -ggdb

SRC=$(shell echo *.c)
OBJ=$(patsubst %.c, %.o, $(SRC))

all: as
as: $(OBJ)
	$(LD) $(LDFLAGS) -o as $(OBJ)

clean:
	rm -f $(OBJ) as
